"""
list_openrouter_free.py — query OpenRouter for currently-available models that
are free at request time, and emit them in our pool-file format.

OpenRouter exposes /api/v1/models with pricing per model; a "free" model has
prompt + completion price both 0 (and typically an `id` suffix of ":free").
We don't trust the suffix alone — some non-:free models can also become free
temporarily; we filter strictly by pricing.

USAGE (from mind-of-tashi/):
  # print to stdout
  python -m tools.list_openrouter_free

  # write a complete pool file (Gemini family + Mistral + Sarvam + OpenRouter free)
  python -m tools.list_openrouter_free --write pools/all-free.txt

The output file is the same format consumed by `python -m tools.selfplay
--opponent-pool-file <path>`.
"""

from __future__ import annotations
import argparse
import os
import sys
import urllib.error
import urllib.request
import json
from pathlib import Path
from typing import Iterable, List, Optional

# allow `python -m tools.list_openrouter_free` from mind-of-tashi/
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(ROOT / ".env")
except ImportError:
    pass


OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"


def fetch_models(api_key: Optional[str] = None) -> List[dict]:
    req = urllib.request.Request(OPENROUTER_MODELS_URL)
    if api_key:
        req.add_header("Authorization", f"Bearer {api_key}")
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data.get("data", [])


def is_free(model: dict) -> bool:
    """A model is currently free if its prompt and completion prices are 0."""
    pricing = model.get("pricing") or {}
    try:
        p = float(pricing.get("prompt", "0") or "0")
        c = float(pricing.get("completion", "0") or "0")
    except (TypeError, ValueError):
        return False
    return p == 0.0 and c == 0.0


def is_chat_capable(model: dict) -> bool:
    """Filter out audio/image/multimodal-output models and meta-routes.

    We want models that produce text-only output from text input — these are
    the ones our chat-completions client can actually drive. Models with
    `out=['text', 'audio']` (e.g. lyria-3) silently return non-conformant
    payloads; `openrouter/free` and `openrouter/owl-alpha` are meta-routers
    whose behaviour we don't control.
    """
    arch = model.get("architecture") or {}
    out_mods = arch.get("output_modalities") or []
    if out_mods and out_mods != ["text"]:
        return False
    mid = model.get("id", "")
    if mid.startswith("openrouter/"):
        return False
    return True


def render_pool(free_ids: Iterable[str]) -> str:
    """Render a complete pool file: header + Gemini + Mistral + Sarvam + OpenRouter free."""
    lines = [
        "# Self-play teacher pool — auto-generated by tools/list_openrouter_free.py",
        "# Per-spec daily limits (see teachers/quota.py): gemini=50, openrouter=200,",
        "# mistral=100, sarvam=100. Override via custom_limits if you know yours.",
        "#",
        "# Lines starting with '#' are comments. Blank lines are ignored.",
        "",
        "# --- Google Gemini (each model id is its own 50/day bucket) ----------",
        "gemini:gemini-2.5-flash",
        "gemini:gemini-2.5-flash-lite",
        "gemini:gemini-2.5-pro",
        "gemini:gemini-3.0-flash",
        "gemini:gemini-3.0-flash-lite",
        "# gemini:gemini-3.5-flash      # uncomment if available on your account",
        "",
        "# --- Mistral free tier -----------------------------------------------",
        "mistral:mistral-small-latest",
        "mistral:mistral-large-latest",
        "",
        "# --- Sarvam (Indian-language native; strongest Hindi/Sanskrit) -------",
        "sarvam:sarvam-m",
        "",
        f"# --- OpenRouter currently-free models ({sum(1 for _ in free_ids)} as of fetch) ---",
        "# Each model has its own daily limit on the free tier (commonly 200/day).",
    ]
    # iterate again — we exhausted the generator counting above
    return "\n".join(lines) + "\n"


def render_pool_with_ids(free_ids: List[str]) -> str:
    body = [
        "# Self-play teacher pool — auto-generated by tools/list_openrouter_free.py",
        "# Per-spec daily limits (see teachers/quota.py): gemini=50, openrouter=200,",
        "# mistral=100, sarvam=100. Override via custom_limits if you know yours.",
        "#",
        "# Lines starting with '#' are comments. Blank lines are ignored.",
        "",
        "# --- Google Gemini (each model id is its own 50/day bucket) ----------",
        "gemini:gemini-2.5-flash",
        "gemini:gemini-2.5-flash-lite",
        "gemini:gemini-2.5-pro",
        "gemini:gemini-3.0-flash",
        "gemini:gemini-3.0-flash-lite",
        "# gemini:gemini-3.5-flash      # uncomment if available on your account",
        "",
        "# --- Mistral free tier -----------------------------------------------",
        "mistral:mistral-small-latest",
        "mistral:mistral-large-latest",
        "",
        "# --- Sarvam (Indian-language native; strongest Hindi/Sanskrit) -------",
        "sarvam:sarvam-m",
        "",
        f"# --- OpenRouter currently-free models ({len(free_ids)} as of fetch) ---",
        "# Each model has its own daily limit on the free tier (commonly 200/day).",
    ]
    for mid in free_ids:
        body.append(f"openrouter:{mid}")
    return "\n".join(body) + "\n"


def main(argv=None) -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--write", type=str, default=None,
                   help="write the rendered pool file to PATH (else stdout)")
    p.add_argument("--limit", type=int, default=None,
                   help="cap the number of free OpenRouter models included")
    p.add_argument("--filter", type=str, default=None,
                   help="substring match — only include models whose id contains this")
    args = p.parse_args(argv)

    api_key = os.environ.get("OPENROUTER_API_KEY", "")
    if not api_key:
        print("[warn] OPENROUTER_API_KEY not set — listing public catalog, "
              "your account may have access to more models", file=sys.stderr)

    try:
        models = fetch_models(api_key)
    except urllib.error.URLError as exc:
        raise SystemExit(f"failed to fetch openrouter catalog: {exc}")

    free = [m for m in models if is_free(m) and is_chat_capable(m)]
    if args.filter:
        free = [m for m in free if args.filter in m.get("id", "")]
    free.sort(key=lambda m: m.get("id", ""))
    if args.limit is not None:
        free = free[: args.limit]

    free_ids = [m["id"] for m in free]
    out = render_pool_with_ids(free_ids)

    if args.write:
        Path(args.write).parent.mkdir(parents=True, exist_ok=True)
        Path(args.write).write_text(out, encoding="utf-8")
        print(f"[ok] wrote {args.write} with {len(free_ids)} OpenRouter free models")
    else:
        print(out)


if __name__ == "__main__":
    main()
